### ISSUE TITLE
Feature request: Remove image?

### ISSUE THREAD

**Issue by tyler36** [alessiomaffeis/vue-picture-input#10]
What's the best way to remove the image after input?

Eg. User fills form, uploads a profile image but decided not to send image before submitting.

Is there a built in method?

**Comment by alessiomaffeis** [comment]
No, I will add it (as an option) ASAP, thanks for pointing it out.

**Comment by tyler36** [comment]
Cheers for the quick response

**Comment by alessiomaffeis** [comment]
Added: 67ef478a9dfffb75b7311fad57660ae4fda7c302

**Comment by alessiomaffeis** [comment]
Added a separate prop for the 'Remove Photo' button's class as well: 5d94b2cc52a02e1e28a5723f66c76a659bbdf39e

**Comment by alessiomaffeis** [comment]
@tyler36 Does it work for you?

**Comment by tyler36** [comment]
Sorry for the late response ... end-of-month craziness.

That's perfect! Thanks for the update, I'm sure others will appreciate the work too.

**Comment by ejlocop** [comment]
please add event emitter to the parent as well.
