### ISSUE TITLE
Update version please 2.1.6 => 2.1.7 npm

### ISSUE THREAD

**Issue by cvaize** [alessiomaffeis/vue-picture-input#102]

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/61518917-205cad80-aa24-11e9-9c90-9c478c48d6fa.png)

**Comment by alessiomaffeis** [comment]
Hi! I merged a bunch of smaller fixes recently and I still need to test it properly. Unfortunately I haven’t setup the automated tests for all the relevant cases, so I will push an update as soon as I can test it thoroughly. ;)

**Comment by cvaize** [comment]
@alessiomaffeis Thanks!
