### ISSUE TITLE
Feature request: Prefill image

### ISSUE THREAD

**Issue by tyler36** [alessiomaffeis/vue-picture-input#11]
I'd like to be able to prefill the image area.

1. Create a article with a main picture.
2. Edit the article and the input box is pre-filled with main picture.

**Comment by alessiomaffeis** [comment]
Article?

**Comment by tyler36** [comment]
Sorry ... My main model is an article -> article has a master picture.

So in my example, my create form will make an article with a title etc. and image (using vue-picture-input').
Later, if I want to edit said article using the same form template, I'd like to be able to pass through the file location string. This would draw the image, where I could use the remove / change button.

**Comment by alessiomaffeis** [comment]
I have finally added an optional **prefill** prop that you can use to specify a default initial picture.

**Comment by alessiomaffeis** [comment]
Let me know if it works for you! @tyler36

**Comment by tyler36** [comment]
Thanks for the update and sorry for slow response (end-of-month crazy)

Works perfectly!.
