### ISSUE TITLE
Limit size is not accurate on iphone safari

### ISSUE THREAD

**Issue by Gazoon007** [alessiomaffeis/vue-picture-input#115]
When the size property was set to 2 MB, on chrome, firefox is working, but on iphone safari, is not working accurately it will applied somewhere between 2.0 - 2.5 MB.

**Comment by alessiomaffeis** [comment]
Hi! Thanks for reporting. It may be due to Safari/iOS calculating MB as 1000 bytes instead of 1024, but maybe I am wrong.  Anyway, client-side limits shouldn't be considered 100% reliable, so I don't think it's worth digging deeper into this one.
