### ISSUE TITLE
prefill url  query string appended to file type

### ISSUE THREAD

**Issue by MordiSacks** [alessiomaffeis/vue-picture-input#118]
I noticed that when i use a prefill url that has query params
e.g.
`https://example.com/pic.jpg?key=sdfghuety98esgfh`

then the file type is
`image/jpeg?key=sdfghuety98esgfh`

I think the issue is on line 524
```js
let mediaType = options.mediaType || ('image/' + (options.fileType || fileName.split('.').slice(-1)[0]))
```

**Comment by alessiomaffeis** [comment]
This will be fixed in the next release, thanks!
