### ISSUE TITLE
Uploaded Image overflows the fixed navbar on scrolling 

### ISSUE THREAD

**Issue by Surajit321** [alessiomaffeis/vue-picture-input#134]
I am using vue-picture-input package to upload my picture. But the uploaded picture/picture canva input overflows the navbar on scrolling. Tried external css to reduce the z-index value but that didn't work at all. 

How to fix this issue, anyone?

**Comment by FrideyAlpha** [comment]
This is because Default value of zIndex is 10000
To fix this issue using prop :z-index like this
<picture-input :z-index="1"></picture-input>
