### ISSUE TITLE
Prefill failed to fetch

### ISSUE THREAD

**Issue by IvanRalph** [alessiomaffeis/vue-picture-input#136]
Encountered Prefill: failed to fetch error.

Implementation:
![image](https://user-images.githubusercontent.com/17797727/99672309-2f3af080-2aae-11eb-8596-20e160752a6e.png)

Error encountered:
![image](https://user-images.githubusercontent.com/17797727/99672462-68736080-2aae-11eb-9932-36aba9b6b5e7.png)

Any fix for this?

**Comment by alessiomaffeis** [comment]
Hi @IvanRalph! The web server where the prefilled src image is located has a CORS policy that doesn't allow fetching files from the domain your application is located. You should be able to fix it by adding proper Access Control headers to the image server response: https://jeremyliberman.com/2019/02/11/fetch-has-been-blocked-by-cors-policy.html

**Comment by joaolisboa** [comment]
I have this issue but only with this package. Even bootstrap-vue with the BAvatar component correctly loads the image. I have no control over the server where the image is stored so fixing it on that end is not a solution, but since bootstrap can load the image why doesn't this one work?
