### ISSUE TITLE
 SyntaxError Unexpected token '<' after a refresh

### ISSUE THREAD

**Issue by JR-Utily** [alessiomaffeis/vue-picture-input#139]
Hello !
Your module seems very great, I like the simplicity to use it.

But whenever I had it in my nuxt app, I can't refresh (F5) the page any more.

Here is a really simple page with just the component set:

```
<template>
  <div>
      <h1 class="title">
Upload Cards
</h1>

<!-- No input yet :) -->

</div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'

import PictureInput from 'vue-picture-input'


@Component({
  components: {
    PictureInput
  }
})
export default class CardsIndex extends Vue {
}

</script>
```

It display well first time I access the page, but if I F5 (or if I save the file again in dev mode...) it shows:
![image](https://user-images.githubusercontent.com/1372453/103456105-5f072600-4cf3-11eb-8d8d-6b5a2d5967e5.png)

The important frame may be this one:
![image](https://user-images.githubusercontent.com/1372453/103456124-8e1d9780-4cf3-11eb-97cf-376c10716937.png)

I'm still discovering Vue.js and Nuxt at the moment, so maybe it is not related to your module and it is a regular newbie issue :)

**Comment by keahie** [comment]
Actually, I have the same problem. I'm using Nuxt 2.14.12 with Vue 2.6.11

**Comment by fcojavierdomenech** [comment]
Any thoughts on this matter?

I've tried [cvaize's](https://github.com/alessiomaffeis/vue-picture-input/issues/99#issuecomment-513098918) solution but didn't work for me. Nuxt 2.14.12 also!

**Comment by fcojavierdomenech** [comment]
Ummm fixed it wrapping the component into `<client-only>` tags

**Comment by JR-Utily** [comment]
so you mean that: https://nuxtjs.org/docs/2.x/features/nuxt-components#the-client-only-component ?

**Comment by fcojavierdomenech** [comment]
Yep, I fixed it with:

```
<client-only>
                      <vue-picture-input 
                        ref="pictureInput"
                        width="128" 
                        height="98" 
                        margin="16" 
                        accept="image/jpeg,image/png" 
                        size="10" 
                        button-class="btn"
                        :custom-strings="{
                        upload: '<h1>Bummer!</h1>',
                        drag: 'Drag a 😺 GIF or GTFO'
                        }"
                        @change="onImageChange">
                      </vue-picture-input>
                    </client-only>
```

And also on my `nuxt.config.js`:
```
// Plugins to run before rendering page (https://go.nuxtjs.dev/config-plugins)
  plugins: [
      '~/plugins/vue-api-query',
      '~/plugins/filters',
      { src: '~/plugins/vue-picture-input', ssr: false }
  ],
```
