### ISSUE TITLE
[Bug] It does not upload anything on submit

### ISSUE THREAD

**Issue by damianciancio** [alessiomaffeis/vue-picture-input#141]
I'm submitting a form, here's the payload. The first field is the picture-input field and the second is a regular <input type="file" ....>

I'm trying to upload the same picture in both cases.

-----------------------------29268506052054927984798431167
Content-Disposition: form-data; name="dni_front_picture"; filename=""
Content-Type: application/octet-stream

-----------------------------29268506052054927984798431167
Content-Disposition: form-data; name="selfie_picture"; filename="Captura de pantalla de 2021-04-07 09-00-07.png"
Content-Type: image/png

PNG

..........................

**Comment by alessiomaffeis** [comment]
Should be fixed in 3.0.1
