### ISSUE TITLE
Impossible to add custom id

### ISSUE THREAD

**Issue by emavitta** [alessiomaffeis/vue-picture-input#148]
Even though i set the id as a prop to the component, in the frontend it keeps printing 
```
id="picture-input" class="picture-input"
```
As per 
https://github.com/alessiomaffeis/vue-picture-input/blob/c2e1241f632d932c4326848237c6465239185001/PictureInput.vue#L2
the id is not updated by the prop id.

**Comment by logovitta** [comment]
suggested fix
```
:id="id||'picture-input'"
```
i'll try to make a pr

**Comment by logovitta** [comment]
damn i've just read better the docs... the id is for the input and it works. Nonetheless i think ti could be necessary to add an idcontainer prop, preventing duplicate id if the component is used more then once in the same page.
