### ISSUE TITLE
How can I use this with Browserify?

### ISSUE THREAD

**Issue by mheiber** [alessiomaffeis/vue-picture-input#23]
Thanks for creating and sharing this library!

It works great for me with Webpack, but Browserify+Vueify is choking on the single-file-component syntax:

```
SyntaxError: Unexpected token: operator (<) while parsing file: /Users/maxheiber/project/node_modules/vue-picture-input/PictureInput.vue
```

When I copy PictureInput.vue into the same directory as the one from which I'm `require`ing it everything works fine. Maybe Browserify doesn't like applying transforms inside `node_modules`?

As a workaround, in our Gulp script, I tried:

```js
browserify().require(files).transform(vueify, {global: true})
```

instead of:

```js
browserify().require(files).transform(vueify, {}})
```

but it made no difference.

Do you have any recommendations? If there's no easy fix for Browserify, would you accept a PR for adding a build step to vue-picture-input?

**Comment by alessiomaffeis** [comment]
Hi!
Uhm, weird. Unfortunately, I don't have extensive experience with Browserify... What solution would you suggest?

**Comment by mheiber** [comment]
@alessiomaffeis we ended up going in a different direction, so no longer need to adapt this library. Thank you very much for your responsiveness and help, and for sharing your source, which is really helpful for seeing some of the gotchas with drag and drop.

Theoretically, the thing I was trying with Browserify and Gulp should have worked. So I'd like to close this issue since no one else reported any problem.

Thanks again!
