### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by ChuiSauCE** [alessiomaffeis/vue-picture-input#25]
Responsive part is not realy working. I'm trying to use it small sized like 200x200 and text and the borders are going crazy. is it only me?

**Comment by alessiomaffeis** [comment]
You are right, it adapted to the viewport width only. I have fixed that, please update to 1.13.1 and let me know if it works for you.
P.S. I have also added a property that allows to hide the inner border and text altogether, FYI:
> plain: (boolean, optional) Set :plain="true" to remove the inner border and text. Default value: false.

**Comment by ChuiSauCE** [comment]
Works way better :) thanks for response
