### ISSUE TITLE
z-index goes over everything

### ISSUE THREAD

**Issue by ChuiSauCE** [alessiomaffeis/vue-picture-input#26]
It's not that hard to fix on flow but it goes over everything if you don't have relative z-index: 0.

I guess it wont be hard to fix it good luck :)

**Comment by alessiomaffeis** [comment]
Do you mean it is too high? I can look into adding a prop for that.

**Comment by alessiomaffeis** [comment]
I have added a prop:

`- **zIndex**: (number, optional) The base z-index value. In case of issues with your layout, change *:zIndex="..."* to a value that suits you better. Default value: 10000.`

**Comment by ugurarici** [comment]
Hello @alessiomaffeis 
Why do we need a high value as 10000 by default?

Most of people uses bootstrap on web projects and bootstraps' highest z-index is 1070
Check here: https://getbootstrap.com/docs/4.1/layout/overview/#z-index

So with 10000 as default, picture-input places itself above everything on bootstrap :))

I saw you added an prop for it but maybe we can set the default z-index to 900, what do you think?
