### ISSUE TITLE
:prefill emits change

### ISSUE THREAD

**Issue by ChuiSauCE** [alessiomaffeis/vue-picture-input#27]
:prefill emits change. which is not that logical since its prefill? not a change?

**Comment by alessiomaffeis** [comment]
While I can see your point, it is still a change from the picture input's perspective (plus, it is only emitted if the picture is actually loaded by the FileReader).

I don't feel comfortable with changing this behaviour, since it could break existing code for some. On the other hand, it should be fairly easy to account for that in the parent component.

**Comment by aldrakos** [comment]
I second that: main issue is that for a normal use case like having a e.g. bg.url prop on the :prefill, and then onChange, also changing the bg.url with the new (uploaded and returned) url, will also cause the :prefill to re-fire the onChange event, which in turn will upload the same file, and loop on forever.

I "fixed" this by sending a unique string param to the onChange fn (e.g. 'im1') and using an extra array to   only allow upload if array['im1'] is true, and if not, set it to true (for next time = "normal"/ User change). Then after upload, before I update the bg.url, I set it to false.

I guess it could also work by using the onClick event to toggle a canUpload var in the same way.

I need to use something like this, cause I am using the onChange functionality on a mixin, and all the components using it have different number of vue-picture instances.

So I also think that prefill should not emit an onChange event, as that is mainly used to detect begin the upload process. It could emit a different even like, onPrefill, for people needing this callback.

As for breaking changes, this is what versioning is for :)

**Comment by Garito** [comment]
Hi!
I understand the point about changing the default behaviour of the prefill but perhaps its time to bump up the major version
Emitting onChange on the prefill is incorrect (I'm agree with @ChuiSauCE)
Perhaps it must emit onPrefill and then onChange

Please be clear about this change cause I prefer to change the library than to make work arounds like the one @aldrakos points

**Comment by alessiomaffeis** [comment]
I agree to change that behaviour and to bump the major version. I’ll do it ASAP!

**Comment by alessiomaffeis** [comment]
It should be fixed now (and I've just bumped the major version to avoid compatibility issues).
Let me know if it doesn't work, and I'll reopen the issue.

**Comment by Garito** [comment]
Thanks!
