### ISSUE TITLE
Preload outer-source

### ISSUE THREAD

**Issue by ChuiSauCE** [alessiomaffeis/vue-picture-input#31]
I'm using outer source for my images. and on preload that's not accepted. there is a way to enable it?

` preloadImage (source) {
      if (typeof source === 'object') {
        this.imageSelected = true
        this.image = ''
        if (this.supportsPreview) {
          this.loadImage(source)
        } else {
          this.$emit('change')
        }
        return
      }
      let headers = new Headers()
      headers.append('Accept', 'image/*')
      fetch(source, {
        method: 'GET',
        mode: 'same-origin',
        headers: headers
      }).then(response => {
        return response.blob()
      })
      .then(imageBlob => {
        let e = { target: { files: [] } }
        const fileName = source.split('/').slice(-1)[0]
        let fileType = fileName.split('.').slice(-1)[0]
        fileType = fileType.replace('jpg', 'jpeg')
        e.target.files[0] = new File([imageBlob], fileName, { type: 'image/' + fileType })
        this.onFileChange(e)
      })
      .catch(err => {
        console.log('Failed loading prefill image: ' + err.message)
      })
    }
  },`

**Comment by alessiomaffeis** [comment]
I have now changed the request mode to 'cors'.
Please note that the external resource must be served with a compatible origin header: https://developers.google.com/web/ilt/pwa/working-with-the-fetch-api#cross-origin_requests

**Comment by gepopp** [comment]
Hello,
i have the same issue when trying to prefill from a url from the s3 server.
is there an option to handle that?

**Comment by pudjamansyurin** [comment]
i am stuck too

**Comment by Naggi-Goishi** [comment]
Me too with firestore storage

**Comment by TeTiRoss** [comment]
is there any solution for this? I also got stuck with Sw image not able to load on prefill.

**Comment by rlisper** [comment]
Hello guys! I think it because of the code block at 514 line of PictureInput.vue: 
if (source.indexOf('data:') === -1) {
        if (source.indexOf('?') !== -1) {
          source += '&_=' + (new Date().getTime())
        } else {
          source += '?_=' + (new Date().getTime())
        }
      }

It change the source link. As result I got error from was S3: The request signature we calculated does not match the signature you provided. Check your key and signing method. Without this addition link works fine
