### ISSUE TITLE
Drag and drop of URLs

### ISSUE THREAD

**Issue by jmaister** [alessiomaffeis/vue-picture-input#34]
In my app, I would like to allow users to drag and drop an image from a different webpage.

If I drop an image it shows an error:
![image](https://user-images.githubusercontent.com/374021/30772842-2e613500-a05c-11e7-9344-a72021a26099.png)

Would it be possible to fire a different event to process the drop data in a different way ?

There is a sample of what I cant to accomplish: http://jsfiddle.net/kkcMH/7/

**Comment by alessiomaffeis** [comment]
I am open to add support for handling images dropped from webpages, as long it doesn't disrupt the current use cases. If you think that is possible, feel free to create a pull request.
