### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by nicholaschun** [alessiomaffeis/vue-picture-input#36]
Please how do i display an image from a database in the preview panel of vue-picture-input..
Anybody have any idea?

**Comment by alessiomaffeis** [comment]
I am sorry, but I really don't understand what you are trying to achieve. Care to share more context and some examples?

**Comment by nicholaschun** [comment]
Thank you very much...
so after uploading an image with the picture input plugin  and inserted
into the database  i want to display the uploaded image in the preview
panel of the same picture input..



​

**Comment by alessiomaffeis** [comment]
As a principle, I wouldn't save an image in a database, but if that is really what you need to do, you could save it in base64 (you can get the base64 string from `this.$refs.pictureInput.image`), and then use that value to set the prefill option as per the README:

> - **prefill**: (image url or File object, optional) use this to specify the path to a default image (or a File object) to prefill the input with. Default value: empty.
> - **prefillOptions**: (object, optional) use this if you prefill with a data uri scheme to specify a file name and a media or file type:
> ```
>   fileName: (string, optional) the file name
>   fileType: (string, optional) the file type of the image, i.e. "png", or
>   mediaType: (string, optional) the media type of the image, i.e. "image/png"

**Comment by nicholaschun** [comment]
Thank you very much .. this was helpful i was able to achieve what i wanted.

**Comment by alessiomaffeis** [comment]
I am glad it was! :) 
P.S. don't forget to star the project, if you find it useful.
