### ISSUE TITLE
Multiple Instances Causing Error

### ISSUE THREAD

**Issue by adamdpate** [alessiomaffeis/vue-picture-input#37]
When using multiple instances of the component, adding an image to any instance but the last one gets the response `FileReader API not supported`. 

However after adding an image to the last instance of the component, everything works as expected. Meaning if I start by placing an image in the last instance, I can go back to early instances and place images with no issue. Not sure why separate components would be interacting in this way.

To clarify the image itself appears, but the `this.$refs.pictureInput.file` reference is empty.

**Comment by adamdpate** [comment]
I decided to just wrap vue-picture-input in a parent component. Originally I wanted to do everything by calling multiple instances and then recording which one was used, but a parent component turned out to be easier. Thanks for your work on this!

**Comment by alessiomaffeis** [comment]
Hi! I am happy you managed to solve the issue. :) That's really weird though, I really don't know how to reproduce the issue. Care to share some code to provide more context?

Thanks again, and don't forget to star the project, if you find it useful!
