### ISSUE TITLE
Empty 'file' with .ico file

### ISSUE THREAD

**Issue by Lorempn2** [alessiomaffeis/vue-picture-input#43]
If I upload an ICO file, the name and type in file in $ref is empty and not regonized by the server.

Edit: Fixed by using an other ico file. File was probely invalid.

Edit 2: Issue still valid, i have to change an ico in order to get the correct file. Strange issue..

**Comment by alessiomaffeis** [comment]
ICO files? 😀I am kinda curious about your specific use case, but I am actually surprised it (partially) worked.

As far as I know, ICO is a container format for BMP or PNG, so it may be related to the format of the encapsulated image.

To be honest, unless it's an quick & easy fix (I have no idea about it, maybe you know more about it) I don't think that supporting ICO should be in the scope of the project.

**Comment by Lorempn2** [comment]
Haha yes! Well, we want to provide our customers the opportunity the upload a favicon in to some backend system. A favicon file is an .ico file :)

Op 8 nov. 2017, om 17:43 heeft Alessio Maffeis <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


ICO files? 😀I am kinda curious about your specific use case, but I am actually surprised it (partially) worked.

As far as I know, ICO is a container format for BMP or PNG, so it may be related to the format of the encapsulated image.

To be honest, unless it's an quick & easy fix (I have no idea about it, maybe you know more about it) I don't think that supporting ICO should be in the scope of the project.

**Comment by alessiomaffeis** [comment]
Have you considered using PNG or GIF instead of ICO? https://en.wikipedia.org/wiki/Favicon#File_format_support

**Comment by Lorempn2** [comment]
Thanks, thats actually a perfect option. Browser support seems to be fine. Thank you very much!

Op 8 nov. 2017, om 17:50 heeft Alessio Maffeis <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Have you considered using PNG or GIF instead of ICO? https://en.wikipedia.org/wiki/Favicon#File_format_support<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FFavicon%23File_format_support&data=02%7C01%7Cmarcel1992%40live.nl%7C32bf68fe06134bc5bc5c08d526c8dc30%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636457566473683427&sdata=CFyJnSqiQf7mdxIfoWeaMSmYju%2F7lmjMTtSQb36cVKQ%3D&reserved=0>

**Comment by alessiomaffeis** [comment]
Awesome! ☺️
Don't forget to star the project, if you find it useful!
