### ISSUE TITLE
How to POST image using axios

### ISSUE THREAD

**Issue by ankush981** [alessiomaffeis/vue-picture-input#44]
Hello,

I'm not having much success sending the image data as POST using axios and this plugin. Here's what my request looks like:

```
this.axios.post(
    this.getApiBaseUrl + '/partners/' + this.getPartnerId + '/basic-details', 
    {
         profile_photo: this.$refs.profilePic.image,
    }
);
```

At the backend, the `profile_photo` variable arrives as a string, and not as a file object. Any help will be much appreciated!

**Comment by Garito** [comment]
In that particular format, perhaps?: data:[<mediatype>][;base64],<data>

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

**Comment by ankush981** [comment]
Than you! I didn't know this was a Data URI. :+1:

**Comment by Garito** [comment]
Was using it before and deal with it too :)
Your welcome
