### ISSUE TITLE
Can preview-container's width, height support many type of length unit?

### ISSUE THREAD

**Issue by hiepvv** [alessiomaffeis/vue-picture-input#48]
Can `vue-picture-input` support other length unit, it's just support pixels right now.
Eg: 
```
<picture-input 
        ...
        width="100%">
</pictute-input>
```

**Comment by alessiomaffeis** [comment]
Hi! Yes, it’s pixels, but they are just the maximum values for width and height, and the dimensions are going to be constrained by the size of the container element.
