### ISSUE TITLE
height calculation when hidden at load

### ISSUE THREAD

**Issue by monsdroid** [alessiomaffeis/vue-picture-input#49]
Hi,

i mount the component in a structure which is `display:none` at first. when i get to the step where the component should be displayed a lot of `heights:0` appear and the component wont show up.

Im using https://vuetifyjs.com/components/steppers but regardless the parent component i think it behaves the same if mounted in a hidden component.

**Comment by dzung1nguyen** [comment]
Same issue with you, it will show when window resize.

**Comment by alessiomaffeis** [comment]
I think I may know what’s the issue, I will look into that.

In the mean time, you could try mounting the component only when the parent is visible.

**Comment by coolcorey** [comment]
Hacky, but
`  mounted() {
    // until PictureInput is fixed
    setTimeout(() => {
      var evt = document.createEvent('UIEvents')
      evt.initUIEvent('resize', true, false, window, 0)
      window.dispatchEvent(evt)
    }, 500)
  }`

**Comment by toonztudio** [comment]
@coolcorey Thank you. It works!

for a deprecated reason, I made a little bit change to

setTimeout(() => {
      const evt = new UIEvent('resize');
      window.dispatchEvent(evt);
    }, 500);
