### ISSUE TITLE
Does not display inside of bootstrap modal

### ISSUE THREAD

**Issue by EddyTheDove** [alessiomaffeis/vue-picture-input#50]
As the title suggests, if you call the component from inside a Bootstrap modal, it does not display at all. Outside the modal, it displays properly.

**Comment by alessiomaffeis** [comment]
Hi! Is it a matter of z-index? Which version of Bootsrap?

**Comment by theharshin** [comment]
Doesn't work inside the bootstrap modal. I'm using bootstrap-vue and the issue is not related to z-index I think. The elements are rendered with height:0. The issue is due to hidden modal. When modal is hidden, the component is being rendered and thus setting height as 0.

**Comment by juanledesma** [comment]
Solución: 
colocar v-if="modal" en el div contenedor. así muestra el div cuando se abre la ventana modal.

<div v-if="modal" class="col-md-5 col-lg-3 " align="center">
                                <picture-input v-bind:prefill="avatar" v-bind:width="ancho" v-bind:height="alto"
                                               ref="pictureInput"
                                               @change="onChanged()"
                                               margin="16"
                                               accept="image/jpeg,image/png"
                                               size="10"
                                               :removable="true">
                                </picture-input>
                            </div>

saludos!!!

**Comment by alessiomaffeis** [comment]
Yep, @juanledesma tip should do it.

**Comment by fredbombadil** [comment]
I've just had this issue as well - v-if="modal" or v-if="b-modal" didn't work for me. The picture-input is being rendered at a calculated 0px height, but if you resize the window, it appears.

**Comment by fredbombadil** [comment]
Having the same issue and I haven't been able to resolve it via @juanledesma method. Height calculated at 0px, so empty looking div, but it appears on window resize.

**Comment by webdeveloper0418** [comment]
I used "v-if', but it doesn't work

**Comment by webdeveloper0418** [comment]
Picture-input never show in modal.
Only when browser size changes, I can see it

**Comment by juanpscotto** [comment]
any news?

**Comment by sushant12** [comment]
@alessiomaffeis  this issue should not be closed yet. The bug still exists.

**Comment by sushant12** [comment]
To everyone who gets stuck with this bug, here is how you can get it working.

vue-picture-input calls `onResize()` during `mounted()` hook which we can use to render the component

```
  openNewPortfolio() {
      $("#newPortfolio").modal(); // opens the modal
      window.setTimeout(() => {
        this.$refs.portfolioImg.onResize();
      }, 1000); //runs onResize() after a second 
    },
```

**Comment by tarang19** [comment]
Can you give me the full code link or code ?
