### ISSUE TITLE
fails on prefill in ie11

### ISSUE THREAD

**Issue by kroegen** [alessiomaffeis/vue-picture-input#51]
ie11 doesn't support File constructor OOB
I fixed this with next code found here https://github.com/jimmywarting/FormData/issues/11 :
let File = window.File

try {
  new File([], '')
} catch(e) {
  File = class File extends Blob {
    constructor(chunks, filename, opts = {}){
      super(chunks, opts)
      this.lastModifiedDate = new Date()
      this.lastModified =+ this.lastModifiedDate
      this.name = filename
    }
  }
}

**Comment by alessiomaffeis** [comment]
Great, thanks for the heads-up! Would you mind to create a PR? :)
