### ISSUE TITLE
vue does not reuse picture-input component

### ISSUE THREAD

**Issue by measwel** [alessiomaffeis/vue-picture-input#52]
I have a vue component - lets call it 'parent' - which has picture-input as a child component. In html I render picture-input as:

```
        <picture-input id='profilePictureInput'
                       ref="pictureInput"
                       v-if="credentials.publish_profile === 'true'"
                       @change="imageHasChanged"
                       @remove="imageRemoved"
                       accept="image/jpeg, image/png, image/jpg"
                       size="0.5"
                       margin="0"
                       :crop="false"
                       :width="400"
                       :height="256"
                       :removable="true"
                       :hideChangeButton="true"
                       removeButtonClass="ui red button"
                       v-bind:customStrings="customPictureInputStrings">
        </picture-input>
```

The problem is, that each time the router navigates to the parent, picture-input is rendered only once in html ( which is okay ) but it creates a new picture-input vue component. In effect, I end up with multiple picture-input vue components. If I then run a function of picture-input, it gets called multiple times, once in each picture-input vue component...

How can I make sure that picture-input only creates one picture-input vue component for given id ? Is the behaviour I am getting the result of a bug in picture-input or am I doing something wrong?

**Comment by alessiomaffeis** [comment]
Hi. I am not able to reproduce the issue, so I don't know how to help you. Just make sure you don't have any reference to the image string or object around in your code (which could be the case if you accessed it using a $ref: `this.$refs.pictureInput.image`).

**Comment by measwel** [comment]
I believe the problem was caused by not reusing vue components. It seems gone after adding keep alive to the router like so:

    <keep-alive>
      <router-view></router-view>
    </keep-alive>

This makes sure components are not recreated, including picture input.

**Comment by alessiomaffeis** [comment]
Good to know, thanks!
