### ISSUE TITLE
[REQUEST] Multi-Images upload feature, please

### ISSUE THREAD

**Issue by ezekielloves** [alessiomaffeis/vue-picture-input#54]
It will be great, if you can add a feature to upload multiple images instead of just one.
Great job, Alessio

**Comment by alessiomaffeis** [comment]
Thank you for the suggestion and the kind words, but unfortunately I don’t think this is in the scope of the project, at least at the moment. If you have any suggestion on how to do it without introducing breaking change, feel free to add them to this thread.

**Comment by alessiomaffeis** [comment]
Thanks, I will look into it as soon as I come back from vacation ;)
