### ISSUE TITLE
How to use this library via CDN?

### ISSUE THREAD

**Issue by TheAndroidGuy** [alessiomaffeis/vue-picture-input#56]
Hello, thanks for this library but how can i use it via CDN?

**Comment by alessiomaffeis** [comment]
Hi! I haven't compiled the component for direct import in the browser (yet), but you should be able to do it with the vue CLI:

**To distribute component:**

```bash
$ vue build PictureInput.vue --prod --lib
```

This will create an optimized bundle in UMD format, and the name of exported library is set to `Component`, you can use `--lib [CustomLibraryName]` to customize it.

```bash
$ vue build -h
```

(source: https://github.com/vuejs/vue-cli/blob/v2.8.0/docs/build.md) 

You can easily install vue-cli through npm: `$ npm install -g vue-cli`

**Comment by alessiomaffeis** [comment]
UPDATE! You can now use it directly in the browser through [unpkg's CDN](https://unpkg.com/vue-picture-input) (or [jsDelivr](https://cdn.jsdelivr.net/npm/vue-picture-input)):

```html
<!DOCTYPE html>
<html>
<head>
  <script src="https://unpkg.com/vue"></script>
  <script src="https://unpkg.com/vue-picture-input"></script>
  <title>In the browser!</title>
</head>
<body>
  <div id="app">
    <p>{{ message }}</p>
    <picture-input></picture-input>
  </div>
  <script>
    var app = new Vue({
      el: '#app',
      data: {
        message: 'Hello Vue!'
      },
      components: {
        'picture-input': PictureInput
      }
    })
  </script>
</body>
</html>
```

**Comment by TheAndroidGuy** [comment]
Awesome Alessio, can't wait to get home and try it. Thank you 🙇
