### ISSUE TITLE
vue-picture-input typeScript definition files (.d.ts)

### ISSUE THREAD

**Issue by abritopach** [alessiomaffeis/vue-picture-input#58]
Fantastic component @alessiomaffeis  It would be great if it could be used in a Vue + Typescript project without the need to use 

`declare var PictureInput: any;`

¿It would be possible to add TypeScript definition files (.d.ts)?

Thanks you!!

**Comment by alessiomaffeis** [comment]
Hi @abritopach, thank you very much, glad you found it useful!
If you think it can help Typescript developers, you can file a pull request. :) I will be happy to accept it, as long as it is non-breaking for non-Typescript users.
