### ISSUE TITLE
Remove event emitted also when component is destroyed

### ISSUE THREAD

**Issue by ennoucas** [alessiomaffeis/vue-picture-input#61]
Hi, 
When watching prefill var, this.removeImage() is triggered when the component is destroyed : 
```
watch: {
    prefill () {
      if (this.prefill) {
        this.preloadImage(this.prefill, this.prefillOptions)
      } else {
         this.removeImage()
      }
    }
  }
```

I am instancing the picture input component with a for loop in Vue JS. When the user clicks on the remove button, a first "remove" event is triggered. Then I catch the event to remove the image from my array which computes the for loop. At this point, the picture-input component is removed from the UI and a second "remove" event is triggered (which I don't want to catch). 

Could be nice if we had the option to choose whether or not to trigger a "remove" event when the component is destroyed or if it was a different event.

**Comment by alessiomaffeis** [comment]
I'm not sure I have a good way to solve this.
