### ISSUE TITLE
Optional height and/or width

### ISSUE THREAD

**Issue by steveops** [alessiomaffeis/vue-picture-input#62]
This is a very nice plugin, with all the options I can imagine! Good job!

I however cant seem to achieve a rather trivial thing here: 
I have to specify both height and width or leave both. If I specify height only or width only it doesn't show

What I want to achieve is very simple: adapt the full width of the container i.e 100%, but specify a height, maybe 300px. How can I achieve this?

**Comment by alessiomaffeis** [comment]
Hi @steveops, it should work without specifying it, so it may be a regression. I will look into it.

**Comment by steveops** [comment]
Thanks. Update when you dig up something

**Comment by tpharaoh** [comment]
I had same issue

**Comment by alessiomaffeis** [comment]
3.0.1 will fix this
