### ISSUE TITLE
[Request] Add remove & change slots

### ISSUE THREAD

**Issue by BennyAlex** [alessiomaffeis/vue-picture-input#64]
Hey,
it would be nice to have two slots: remove and change to specify an own component for these actions.
When clicking on the slot item, it will call the right methods to remove or to change the image.

**Comment by bielslima** [comment]
Any updates on the case?

**Comment by alessiomaffeis** [comment]
I wanted to keep it simple with the buttons, but if you can add the slots without changing the default behaviour for everybody else, you are welcome to open a PR! :)
