### ISSUE TITLE
Height set to 0 when inside a hidden element

### ISSUE THREAD

**Issue by MattApril** [alessiomaffeis/vue-picture-input#70]
I have vue-picture-input inside of a bootstrap collapse that is hidden on page load.
When expanding the collapsed element the picture is set to height 0 even though i've specified a height and width in the props.

Looks like the initial call to onResize might be the culprit..

Currently I am working around this by wrapping the component in a v-if to only render when the parent div is displayed. But it would be nice if it was set to the correct height initially, because the hieght calculation done by the bootstrap collapse is thrown off as a result, and the expand animation  jumps once this component renders.

**Comment by alessiomaffeis** [comment]
Do you have a sample page with vue-picture-input in a bootstrap collapse to try it out?
This is not the first time people have issues with the component inside bootstraps elements, but I still am not sure if there is an easy way to fix this and if that should be the default behaviour.

**Comment by MattApril** [comment]
The issue is not with bootstrap, that was just my example, it is about being initially rendered inside a hidden element. The root of the issue is demonstrated here: https://codesandbox.io/s/53xz328qwx

If "showContainer" in my component is initiated as false the picture input renders incorrectly, with a height of 0. But if you initiate it as true, it renders properly.

**Comment by lasthead** [comment]
Faced the same. The pop-up window does not give this element height or width. Temporarily decided to stylize blocks using !important. 

I would like to know the right solution

**Comment by Christilut** [comment]
Same problem here but with Vuetify when the picture input is in a tab that is loaded but not yet displayed.

**Comment by CavalcanteLeo** [comment]
Same here inside a vuetify dialog

**Comment by kedrovski** [comment]
The same problem, when use component inside Bootstrap-modal (Bootstrap-vue)

**Comment by kedrovski** [comment]
If you this issue when 'vue-picture-input' inside Bootstrap-modal (Bootstrap-vue) here is a fix:
`mounted() {
        this.$root.$on('bv::modal::shown', (bvEvent, modalId) => {
            console.log('Modal is about to be shown', bvEvent, modalId);
            this.$nextTick(function () {
                // DOM updated
                window.dispatchEvent(new Event('resize'));
            });
        })
    },`

**Comment by nmfzone** [comment]
Other solution that worth to try, use the [`vue-observe-visibility`](https://github.com/Akryum/vue-observe-visibility) plugin.
Then, on `visibilityChanged`, just call `window.dispatchEvent(new Event('resize'));`

Example:

```
<template>
  <picture-input 
      width="600" 
      height="600" 
      margin="16" 
      accept="image/jpeg,image/png" 
      size="10" 
      v-observe-visibility="visibilityChanged"
      button-class="btn" />
</template>

<script>
export default {
  methods: {
    visibilityChanged () {
      window.dispatchEvent(new Event('resize'));
    }
  }
}
</script>
```
