### ISSUE TITLE
when used multiple picture-inputs and remove one, picture in canvas stays

### ISSUE THREAD

**Issue by ugurarici** [alessiomaffeis/vue-picture-input#72]
Hello @alessiomaffeis , thanks for this plugin, very useful

I'm trying to use multiple picture-inputs in a component, actually users should add and remove options on a form

So my problem is:
I add multiple picture-inputs, lets say 3 of them
Select a picture for 2nd one
When I deleted 2nd option it should be disappear with it's selection and preview
But instead of that; one option dissappears but preview stays

I know it sounds complicated, so I prepared a demo on jsfiddle: https://jsfiddle.net/ugurarici/eywraw8t/164462/

And for a quick look you can see it in action here: https://gph.is/2uhzBUs

Maybe it's because of the way i constructed it (by creating a loop with photoOptions array and adding and deleting options by adding and deleting new elements to/from photoOptions array)

Thanks again, looking for your answer and suggestions about how to solve it.

**Comment by ugurarici** [comment]
Ok, found the solution: https://vuejs.org/guide/list.html#key

I added an :key="photo" to <picture-input ...></picture-input> and when it deleted from dom it gone with preview

But still wondering what you think about using multiple <picture-input> within a form :))

**Comment by ugurarici** [comment]
Found solution: https://vuejs.org/v2/guide/list.html#key

I added an :key="photo" to div which I use for v-for="photo in photos" and now it works like charm! :))

But still wondering what you suggest to use multiple <picture-input> in one form.

**Comment by alessiomaffeis** [comment]
Great! I think that keying is the right solution, I should probably add it to the README.
