### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by sanju4115** [alessiomaffeis/vue-picture-input#81]
please tell me the way how to use vue-picture-input with nuxt

**Comment by cvaize** [comment]
+1 [new issue](https://github.com/alessiomaffeis/vue-picture-input/issues/99)

**Comment by Albertbol** [comment]
+1

**Comment by alessiomaffeis** [comment]
As per: https://github.com/alessiomaffeis/vue-picture-input/issues/99#issuecomment-594620398
