### ISSUE TITLE
Can I use base64 for prefill ?

### ISSUE THREAD

**Issue by Juckky00** [alessiomaffeis/vue-picture-input#83]
My project have service for get image by return base64 ,because don't want direct access by url image.

How to use base64 data for prefill ?

Please give me some example.

Thank you.

**Comment by sebpalluel** [comment]
Hi,

As explained here : https://stackoverflow.com/questions/47468643/how-to-display-mysql-blob-image-in-html-using-vuejs

You need a function that return the string with the buffer in the right format.
Once you've done that ->`:prefill="dataUrl()"` will do the trick 😉 

`dataUrl() {
      return this.form.avatar
    },`

Here `form.avatar` that i retrieve from the database is already on the format `data:image/png;base64,iVBORw0KGgoAAAANS....`

**Comment by nausech** [comment]
Hi, 

I'm have a problem, when I intent  to insert the base64 image in the property "prefill" I get the alert with the message this file isn't  unsupported file.

thanks

**Comment by valeriopisapia** [comment]
I'm interested in this topic - any news about it?

**Comment by alessiomaffeis** [comment]
This should be fixed in 3.0.0
