### ISSUE TITLE
Add: EXIF orientation removal on upload.

### ISSUE THREAD

**Issue by nicroto** [alessiomaffeis/vue-picture-input#86]
First of all - thanks for the cool tool.

It would be very very helpful if there was a way to strip the orientation EXIF tag and just transfer the image as intended to be viewed.

This way when you actually want to display the image later, you don't need to go through everything that this tool goes to (using canvas, detecting tags and doing transformations etc.) and one can simply display the image.

**Comment by alessiomaffeis** [comment]
Hi! Thank you :) I will consider this and other destructive operations for the next major version.
