### ISSUE TITLE
how to remove the image from the view manually?

### ISSUE THREAD

**Issue by rakibulhaq** [alessiomaffeis/vue-picture-input#93]
I was trying to remove the image when user completes the upload, i have tried the followings but failed:  
1. setting `this.$refs.pictureInput = null`
2. adding `v-model = "image"` so that it may re-render when the image data is changed
3. forcing update() on the component as `this.$refs.pictureInput.$forceUpdate()`

Nothing is working, how can i achieve this?

**Comment by Ayman97** [comment]
I really need this too.

**Comment by rakibulhaq** [comment]
finally i was able to achieve this by accessing the component `removeImage()` method with the help of $ref.
I looked into the component code and found that method:
Using `this.$refs.pictureInput.removeImage()` after image upload solved the issue.
@Ayman97 hope it helps.

**Comment by alessiomaffeis** [comment]
Yes, that should work. I will try to add a more declarative way to do so, in the next version. :)

**Comment by rakibulhaq** [comment]
@alessiomaffeis thanks for this awesome component, please keep up the great work!

**Comment by jamaljalali68** [comment]
this.$refs.pictureInput.removeImage() ........this work for me ....thanks @rakibulhaq
