### ISSUE TITLE
Radius does not clip canvas contents on MacOS/iOS Safari [Proposed Solution]

### ISSUE THREAD

**Issue by shawnratcliff** [alessiomaffeis/vue-picture-input#97]
It appears that the radius property does not work correctly in Apple browsers. The picture-preview canvas element overflows the parent's radius, as shown in the attached image.

<img width="339" alt="Screen Shot 2019-04-09 at 1 21 42 PM" src="https://user-images.githubusercontent.com/14947501/55832451-72f40880-5aca-11e9-90ea-450198893e23.png">

I believe this is due to Safari's unique treatment of stacking contexts. It appears that the problem can be resolved by adding a zero 3d translation on the parent div (thereby creating a new stacking context):

```
<style>
  div.preview-container { transform: translate3d(0,0,0); }
</style>
````

<img width="369" alt="Screen Shot 2019-04-09 at 1 29 08 PM" src="https://user-images.githubusercontent.com/14947501/55832944-7f2c9580-5acb-11e9-8565-b07869f7a6da.png">

**Comment by alessiomaffeis** [comment]
Great catch, i will try to fix it in the next version! :)
