### ISSUE TITLE
BUG in nuxt.js "Unexpected token <"

### ISSUE THREAD

**Issue by cvaize** [alessiomaffeis/vue-picture-input#99]
![image](https://user-images.githubusercontent.com/26907947/60733298-de346600-9f65-11e9-946e-5adabf0b405f.png)
You can recreate the error if you follow the algorithm: 
1) Enter the link [https://codesandbox.io](https://codesandbox.io)
2) 
![image](https://user-images.githubusercontent.com/26907947/60733392-2c496980-9f66-11e9-8e93-ba44b60e1ef9.png)
3)
![image](https://user-images.githubusercontent.com/26907947/60733414-38352b80-9f66-11e9-88d9-81d348206f9c.png)
4)
![image](https://user-images.githubusercontent.com/26907947/60733451-4e42ec00-9f66-11e9-9229-e6987ddbf6e5.png)
5)
![image](https://user-images.githubusercontent.com/26907947/60733478-674b9d00-9f66-11e9-85f0-04c147da2860.png)
6) Looking forward to installing dependencies and restarting nuxt.js 
7) We insert logic directly into index.vue
![image](https://user-images.githubusercontent.com/26907947/60733538-9104c400-9f66-11e9-91fe-e2c14ec7e2c2.png)
![image](https://user-images.githubusercontent.com/26907947/60733609-c7dada00-9f66-11e9-9594-15372e28bc81.png)
![image](https://user-images.githubusercontent.com/26907947/60733652-e9d45c80-9f66-11e9-8d3b-4188c27e1864.png)

**Comment by Albertbol** [comment]
+1, tried no-ssr tags, client loading in nuxt config but nothing works

**Comment by cvaize** [comment]
@Albertbol Works if you connect as a plugin with the flag ssr=false
![image](https://user-images.githubusercontent.com/26907947/61511987-f5695e00-aa11-11e9-9776-4b517d7b345d.png)

**Comment by Albertbol** [comment]
Can you please share your plugin file aswell? 
Thanks

**Comment by cvaize** [comment]
@Albertbol Unfortunately it works without ssr, but it still works
![image](https://user-images.githubusercontent.com/26907947/61512238-b2f45100-aa12-11e9-92dd-852841aab5f7.png)
![image](https://user-images.githubusercontent.com/26907947/61512248-ba1b5f00-aa12-11e9-9e9e-bbd4bc725a27.png)

**Comment by Albertbol** [comment]
Thank you very much I will try it out today!

**Comment by Albertbol** [comment]
It works thank you!

**Comment by cvaize** [comment]
There is another way. Попробуйте еще так, я позже сам попробую. 
![image](https://user-images.githubusercontent.com/26907947/61540792-ca096200-aa57-11e9-95a1-e049fc54f3d8.png)

**Comment by Albertbol** [comment]
Well if i dont write anything to plugin and nuxt config, just adding like your last picture it will give error like : "Render function or template not defined for component  *componentname*" , if i add <no-ssr> around then it will work , but throw this error:
```
 [Vue warn]: Failed to resolve async component: () => __webpack_require__.e(/*! import() */ 0).then(__webpack_require__.bind(null, /*! ~/components/formfields/Test.vue */ "./components/formfields/Test.vue"))
Reason: SyntaxError: Unexpected token <
```

**Comment by cvaize** [comment]
@Albertbol Well, later, when I finish my project. I'll fix it. This will be included in the project optimization.

**Comment by Albertbol** [comment]
Its ok , thanks ;)

**Comment by ABleas** [comment]
Just registering my support for this fix. I too had this problem, and success with the above solution, so thank you, @cvaize !

**Comment by alessiomaffeis** [comment]
I cannot reproduce this issue: I tried importing the component in a nuxt sandbox, and it seems working fine now. Let me know if it's still an issue for you.
